#############################
# LEG 1 
#############################
leg_1_joint_1:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x3B
  #gains: [200.0,0.0,10.0,0.0,0.0]
  gains: [0.01,0.001,0.00004,0.0,0.0]


leg_1_joint_2:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x3B
  gains: [200.0,0.0,10.0,0.0,0.0]

#############################
# LEG 2
#############################
leg_2_joint_1:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x3B
  gains: [200.0,0.0,10.0,0.0,0.0]
  

leg_2_joint_2:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x3B
  gains: [200.0,0.0,10.0,0.0,0.0]

#############################
# LEG 3
#############################
leg_3_joint_1:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x3B
  gains: [200.0,0.0,10.0,0.0,0.0]
  
leg_3_joint_2:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x3B
  gains: [200.0,0.0,10.0,0.0,0.0]

#############################
# LEG 4
#############################
leg_4_joint_1:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x3B
  gains: [200.0,0.0,10.0,0.0,0.0]
  
leg_4_joint_2:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x3B
  gains: [200.0,0.0,10.0,0.0,0.0]
