#############################
# LEG 1 
#############################
leg_1_joint_1:
  #motor_type: FlexPro #allowed HHCM, Circulo, FlexPro, default HHCM
  brake_present: false
  control_mode: 0x00


leg_1_joint_2:
  #motor_type: FlexPro #allowed HHCM, Circulo, FlexPro, default HHCM
  brake_present: false
  control_mode: 0x00

#############################
# LEG 2
#############################
leg_2_joint_1:
  #motor_type: FlexPro #allowed HHCM, Circulo, FlexPro, default HHCM
  brake_present: false
  control_mode: 0x00
  

leg_2_joint_2:
  #motor_type: FlexPro #allowed HHCM, Circulo, FlexPro, default HHCM
  brake_present: false
  control_mode: 0x00

#############################
# LEG 3
#############################
leg_3_joint_1:
  #motor_type: FlexPro #allowed HHCM, Circulo, FlexPro, default HHCM
  brake_present: false
  control_mode: 0x00
  
leg_3_joint_2:
  #motor_type: FlexPro #allowed HHCM, Circulo, FlexPro, default HHCM
  brake_present: false
  control_mode: 0x00

#############################
# LEG 4
#############################
leg_4_joint_1:
  #motor_type: FlexPro #allowed HHCM, Circulo, FlexPro, default HHCM
  brake_present: false
  control_mode: 0x00
  
leg_4_joint_2:
  #motor_type: FlexPro #allowed HHCM, Circulo, FlexPro, default HHCM
  brake_present: false
  control_mode: 0x00
